# Generated by Django 5.1.7 on 2025-03-13 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('sku', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=250)),
                ('retail_price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
