# Generated by Django 5.1.7 on 2025-03-17 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopitem',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
