# Generated by Django 5.1.7 on 2025-03-15 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='shop_user',
        ),
    ]
