# Generated by Django 5.1.7 on 2025-03-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0002_shopitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='retail_price',
            field=models.FloatField(max_length=8),
        ),
    ]
