# Generated by Django 5.1.7 on 2025-03-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0003_alter_item_retail_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
