# Generated by Django 5.1.7 on 2025-03-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0003_shopitem_shop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='xfer_pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shopitem',
            name='xfer_pending',
            field=models.BooleanField(default=False),
        ),
    ]
