# Generated by Django 5.1.7 on 2025-03-17 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0004_alter_item_retail_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='xfer_pending',
        ),
        migrations.RemoveField(
            model_name='shopitem',
            name='xfer_pending',
        ),
    ]
