# Generated by Django 5.1.7 on 2025-03-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0005_remove_item_xfer_pending_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edit_lock', models.BooleanField(default=False)),
            ],
        ),
    ]
