# Generated by Django 5.1.7 on 2025-03-19 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_manager', '0007_transferitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopitem',
            name='id',
        ),
        migrations.AlterField(
            model_name='shopitem',
            name='item',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='stock_manager.item'),
        ),
    ]
